version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    ports:
      - "27017:27017"

  mongo-restore:
    build: 
      dockerfile: ./Dockerfile.mongo-restore
    restart: "on-failure"
    networks:
      - app-network

  password-init:
    image: python:3.12-slim
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "python -c 'import secrets; print(secrets.token_urlsafe(32))' > /run/secrets/backend_password"
    volumes:
      - backend_secret:/run/secrets
    networks:
      - app-network

  backend:
    build: ./backend
    depends_on:
      - mongo
      - password-init
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - JWT_SECRET_KEY_FILE=/run/secrets/backend_password
      - ENV=production
    ports:
      - "8000:8000"
    volumes:
      - backend_secret:/run/secrets
    networks:
      - app-network
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "export JWT_SECRET_KEY=$(cat $JWT_SECRET_KEY_FILE) && exec gunicorn main:app -c gunicorn.conf.py -k uvicorn.workers.UvicornWorker --bind 0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8000    
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  backend_secret:

networks:
  app-network:
    driver: bridge