version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mongo-restore:
    image: mongo:6.0
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./db-backup:/db-backup
    entrypoint: ["mongorestore", "--host=mongo", "--dir=/db-backup/dump", "--drop"]
    restart: "on-failure"
    networks:
      - app-network

  backend:
    build: ./backend
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8000    
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge