apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: wct-stats

build:
  artifacts:
    - image: ghcr.io/shayops2/wct-stats-frontend
      context: frontend
      docker:
        buildArgs:
          REACT_APP_BACKEND_URL: "http://backend.localhost:8081"      
        dockerfile: Dockerfile
        
    - image: ghcr.io/shayops2/wct-stats-backend
      context: backend
      docker:
        dockerfile: Dockerfile

deploy:
  helm:
    releases:
      - name: wct
        chartPath: helm/chart
        setValueTemplates:
          frontend.image.repository: "{{.IMAGE_REPO_ghcr_io_shayops2_wct_stats_frontend}}"
          frontend.image.tag: "{{.IMAGE_TAG_ghcr_io_shayops2_wct_stats_frontend}}"
          backend.backend.image.repository: "{{.IMAGE_REPO_ghcr_io_shayops2_wct_stats_backend}}"
          backend.backend.image.tag: "{{.IMAGE_TAG_ghcr_io_shayops2_wct_stats_backend}}"
        valuesFiles:
          - helm/chart/values-local-dev.yaml
          
