apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: wct-stats

build:
  local:
    push: false
    useBuildkit: true
  artifacts:
    - image: ghcr.io/shayops2/wct-stats-frontend
      context: frontend
      sync:
        infer:
          - "src/**/*.ts"
          - "src/**/*.tsx"
          - "public/**"
      docker:
        target: dev
        buildArgs:
          VITE_BACKEND_URL: "http://backend.localhost"

    - image: ghcr.io/shayops2/wct-stats-backend
      context: backend
      runtimeType: python
      sync:
        infer:
          - "**/*.py"

deploy:
  helm:
    releases:
      - name: wct
        chartPath: helm/chart
        setValueTemplates:
          frontend.image.tag: "{{.IMAGE_TAG_ghcr_io_shayops2_wct_stats_frontend}}"
          backend.image.tag: "{{.IMAGE_TAG_ghcr_io_shayops2_wct_stats_backend}}"
        valuesFiles:
          - helm/chart/values-local-dev.yaml