apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: wct-stats

build:
  local:
    push: false
  artifacts:
    - image: frontend
      context: frontend
      docker:
        target: dev
        buildArgs:
          VITE_BACKEND_URL: "http://backend.localhost"      
        
    - image: backend
      runtimeType: python
      context: backend
      sync:
        infer:
          - '**/*.py'

deploy:
  helm:
    releases:
      - name: wct
        chartPath: helm/chart
        setValueTemplates:
          frontend.image.repository: "{{.IMAGE_REPO_frontend}}"
          frontend.image.tag: "{{.IMAGE_TAG_frontend}}"
          
          backend.image.repository: "{{.IMAGE_REPO_backend}}"
          backend.image.tag: "{{.IMAGE_TAG_backend}}"

        valuesFiles:
          - helm/chart/values-local-dev.yaml
          
