apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: wct-stats

build:
  artifacts:
    - image: frontend
      context: frontend
      docker:
        buildArgs:
          REACT_APP_BACKEND_URL: "http://backend.localhost:8081"      
        
    - image: backend
      context: backend

deploy:
  helm:
    releases:
      - name: wct
        chartPath: helm/chart
        setValueTemplates:
          frontend.image.repository: "{{.IMAGE_REPO_frontend}}"
          frontend.image.tag: "{{.IMAGE_TAG_frontend}}"
          
          backend.image.repository: "{{.IMAGE_REPO_backend}}"
          backend.image.tag: "{{.IMAGE_TAG_backend}}"
        valuesFiles:
          - helm/chart/values-local-dev.yaml
          
