apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-pod-deleter-binding
subjects:
  - kind: ServiceAccount
    name: grafana-infinity-sa
    namespace: monitoring  
roleRef:
  kind: ClusterRole
  name: grafana-pod-deleter
  apiGroup: rbac.authorization.k8s.io
