apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    grafana_datasource: "1"
data:
  infinity-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Infinity
        type: yesoreyeram-infinity-datasource
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          allowDangerousHTTPMethods: true
          tlsSkipVerify: true
          auth_method: bearerToken
          allowedHosts:
           - 'https://kubernetes.default.svc'
        secureJsonData:
          bearerToken: $__file{/etc/shared/infinity-token}
