apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: {{ .Values.service.type }}
  selector:
    app: grafana
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
