kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: allow-token-request-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: allow-token-request
  apiGroup: rbac.authorization.k8s.io