apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-token-request
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]

