image:
  repository: grafana/grafana
  tag: 12.0.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  host: grafana.local

resources: {}

plugins:
  - yesoreyeram-infinity-datasource
  - speakyourcode-button-panel

