# default values for the Helm chart
# This file can be overridden by providing a custom values file when installing the chart

backend:
  command:
    - /bin/sh
    - -c
  args:
    - exec gunicorn main:app -c gunicorn.conf.py -k uvicorn.workers.UvicornWorker --bind 0.0.0:8000
  env:
    - name: ENV
      value: production
    - name: MONGODB_URL
      value: mongodb://__MONGO_HOST__:27017
  envFrom:
  - secretRef:
      name: jwt-token
  - secretRef:
      name: oci-bucket-par
  image:
    repository: ghcr.io/shayops2/wct-stats-backend
    tag: "v1.0.3"
  imagePullSecrets:
    - name: regcred
  imagePullPolicy: IfNotPresent
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  replicas: 1
  strategy:
    type: Recreate
  type: ClusterIP



frontend:
  image:
    repository: ghcr.io/shayops2/wct-stats-frontend
    tag: "0.1"
  imagePullSecrets: 
    - name: regcred
  imagePullPolicy: IfNotPresent
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  replicas: 1
  type: ClusterIP


kubernetesClusterDomain: cluster.local

ingress:
  enabled: true
  annotations:
    enabled_annotations: false
  backend:
    host: backend.example
    paths:
    - /
    className: traefik
  frontend:
    host: frontend.example
    paths:
    - /
    className: traefik

mongo:
  restore:
    envFrom:
    - secretRef:
        name: oci-bucket-par
    imagePullSecrets:
      - name: regcred
    image:
      repository: ghcr.io/shayops2/wct-stats-mongo-restore
      tag: "2.0"
    imagePullPolicy: IfNotPresent


  mongo:
    livenessProbe:
      exec:
        command:
        - mongosh
        - --eval
        - db.adminCommand('ping')
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 5
    args:
    - --bind_ip_all
    image:
      repository: mongo
      tag: "6.0"
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  replicas: 1
  type: ClusterIP
