apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wct-stats
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/shayOps2/wct-stats.git
    targetRevision: main
    path: helm/chart
    helm:
      valueFiles:
        - values-tailscale.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true     