apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.cheetoh-gila.ts.net"  # Vault server URL
      path: "kv-wct"                     # Vault path where secrets are stored
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token-secret"        # Kubernetes Secret containing the Vault token
          namespace: "external-secrets"   # Namespace where the Secret is located
          key: "token"                       # Key in the Kubernetes Secret that contains the token
