apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-jwt
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-dev-secrets
    creationPolicy: Owner
  dataFrom:
  - extract: 
      key: "kv-wct/dev"  # Path to the secrets in Vault