name: Build And Deploy WCT Stats
on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: marceloprado/has-changed-path@v1.0.1
        id: changed-backend
        with:
          paths: backend

      - name: bump version
        if: steps.changed-backend.outputs.changed == 'true'
        run: |
          echo "Bumping version..."
          VERSION=$(cat backend/version.txt)
          VERSION=${VERSION:1}

          IFS='.' read -r major minor patch <<< "$VERSION"    
          COMMIT_MSG=$(git log -1 --pretty=%B)

          echo "Commit message: $COMMIT_MSG"

          # Determine bump type
          if echo "$COMMIT_MSG" | grep -iqE "MAJOR|BREAKING"; then
            major=$((major + 1))
            minor=0
            patch=0
            BUMP_TYPE="major"
          elif echo "$COMMIT_MSG" | grep -iqE "MINOR|feature|add"; then
            minor=$((minor + 1))
            patch=0
            BUMP_TYPE="minor"
          else
            patch=$((patch + 1))
            BUMP_TYPE="patch"
          fi

          NEW_VERSION="v$major.$minor.$patch"
          echo "Bumped $BUMP_TYPE version: $VERSION → $NEW_VERSION"      
          
          echo "$NEW_VERSION" > backend/version.txt
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV


      - name: Build and push backend image
        if: steps.changed-backend.outputs.changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: false
          tags: |
            ghcr.io/shayops2/wct-stats-backend:latest 
            ghcr.io/shayops2/wct-stats-backend:${{ env.VERSION }}

            
      - name: Commit version bump
        if: steps.bump_version.outputs.version != ''
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add backend/version.txt
          git commit -m "CI - Bump version to $VERSION [skip ci]" || echo "No changes to commit"

          # Re-authenticate using token
          REPO_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          git remote set-url origin "$REPO_URL"

          git push origin HEAD:${{ github.ref_name }}
            