name: Build And Deploy WCT Stats
on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: marceloprado/has-changed-path@v1.0.1
        id: changed-frontend
        with:
          paths: frontend

      - name: bump version
        if: steps.changed-frontend.outputs.changed == 'true'
        run: |
          echo "Bumping version..."
          VERSION=$(cat frontend/version.txt)
          VERSION=${VERSION:1}

          IFS='.' read -r major minor patch <<< "$VERSION"    
          COMMIT_MSG=$(git log -1 --pretty=%B)

          echo "Commit message: $COMMIT_MSG"

          # Determine bump type
          if echo "$COMMIT_MSG" | grep -iqE "MAJOR|BREAKING"; then
            major=$((major + 1))
            minor=0
            patch=0
            BUMP_TYPE="major"
          elif echo "$COMMIT_MSG" | grep -iqE "MINOR|feature|add"; then
            minor=$((minor + 1))
            patch=0
            BUMP_TYPE="minor"
          else
            patch=$((patch + 1))
            BUMP_TYPE="patch"
          fi

          NEW_VERSION="v$major.$minor.$patch"
          echo "Bumped $BUMP_TYPE version: $VERSION → $NEW_VERSION"      
          
          echo "$NEW_VERSION" > frontend/version.txt
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: 'Login to GitHub Container Registry'
        if: steps.changed-frontend.outputs.changed == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }} 

      - name: Build and push frontend image
        if: steps.changed-frontend.outputs.changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: frontend
          push: true
          tags: |
            ghcr.io/shayops2/wct-stats-frontend:latest 
            ghcr.io/shayops2/wct-stats-frontend:${{ env.VERSION }}

      - name: Commit version bump
        if: steps.changed-frontend.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Bump frontend version to ${{ env.VERSION }} [skip ci]"
          file_pattern: frontend/version.txt


  backend:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: marceloprado/has-changed-path@v1.0.1
        id: changed-backend
        with:
          paths: backend

      - name: bump version
        if: steps.changed-backend.outputs.changed == 'true'
        run: |
          echo "Bumping version..."
          VERSION=$(cat backend/version.txt)
          VERSION=${VERSION:1}

          IFS='.' read -r major minor patch <<< "$VERSION"    
          COMMIT_MSG=$(git log -1 --pretty=%B)

          echo "Commit message: $COMMIT_MSG"

          # Determine bump type
          if echo "$COMMIT_MSG" | grep -iqE "MAJOR|BREAKING"; then
            major=$((major + 1))
            minor=0
            patch=0
            BUMP_TYPE="major"
          elif echo "$COMMIT_MSG" | grep -iqE "MINOR|feature|add"; then
            minor=$((minor + 1))
            patch=0
            BUMP_TYPE="minor"
          else
            patch=$((patch + 1))
            BUMP_TYPE="patch"
          fi

          NEW_VERSION="v$major.$minor.$patch"
          echo "Bumped $BUMP_TYPE version: $VERSION → $NEW_VERSION"      
          
          echo "$NEW_VERSION" > backend/version.txt
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV


      - name: 'Login to GitHub Container Registry'
        if: steps.changed-backend.outputs.changed == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}


      - name: Build and push backend image
        if: steps.changed-backend.outputs.changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: |
            ghcr.io/shayops2/wct-stats-backend:latest 
            ghcr.io/shayops2/wct-stats-backend:${{ env.VERSION }}

            
      - name: Commit version bump
        if: steps.changed-backend.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Bump backend version to ${{ env.VERSION }} [skip ci]"
          file_pattern: backend/version.txt
